// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdCeg-hdMwqEo333f66q1BxodjEux9nCs',
    appId: '1:390450382470:web:984d9034f38ce12a457307',
    messagingSenderId: '390450382470',
    projectId: 'matchhive',
    authDomain: 'matchhive.firebaseapp.com',
    storageBucket: 'matchhive.appspot.com',
    measurementId: 'G-6RYVXYQFLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEM4ILZIJG6uIRocN8i7GNxPGIFKNmHyQ',
    appId: '1:390450382470:android:ff66c6b846137ead457307',
    messagingSenderId: '390450382470',
    projectId: 'matchhive',
    storageBucket: 'matchhive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-djeYhwYMQouC0SpRYwuFUHi2ozNkAW0',
    appId: '1:390450382470:ios:1b69163eeb8017d5457307',
    messagingSenderId: '390450382470',
    projectId: 'matchhive',
    storageBucket: 'matchhive.appspot.com',
    iosBundleId: 'com.example.playfield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-djeYhwYMQouC0SpRYwuFUHi2ozNkAW0',
    appId: '1:390450382470:ios:1b69163eeb8017d5457307',
    messagingSenderId: '390450382470',
    projectId: 'matchhive',
    storageBucket: 'matchhive.appspot.com',
    iosBundleId: 'com.example.playfield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdCeg-hdMwqEo333f66q1BxodjEux9nCs',
    appId: '1:390450382470:web:a022023160d9740b457307',
    messagingSenderId: '390450382470',
    projectId: 'matchhive',
    authDomain: 'matchhive.firebaseapp.com',
    storageBucket: 'matchhive.appspot.com',
    measurementId: 'G-4VBQXX64HD',
  );
}
